### ISSUE TITLE
Adminsettings - Slideshow-Speed is not showing its stored value

### ISSUE THREAD

**Issue by skaterlui** [agriboed/wordpress-wp-fancybox3#1]
1. Goto Settings
2. Edit Slideshow => Speed, set to 2000ms
3. Save settings
4. Check a Slideshow on a post, speed is 2000ms
5. Open settings again
6. The value 2000 is not in the speed input
7. Save settings without changing anything
8. Check a Slideshow on a post, speed is reset to it's initial value

Speed setting should be stored and the input field should hold the value when settings are opened.

**Comment by agriboed** [comment]
Thank you. It will be fixed in few days.
