### ISSUE TITLE
Captions are not working with galleries

### ISSUE THREAD

**Issue by skaterlui** [agriboed/wordpress-wp-fancybox3#2]
Hello agriboed,

thx 4 your last bugfix! Well done. Maybe you could implement captions for galleries.
Check this link [blogtofakie.de](http://www.blogtofakie.de/archives/12249), most of the pictures have a caption.
The caption is only shown for the first picture of the post which is not part of the gallery.

Reprosteps:
Add a gallery like this [gallery link="file" ids="12709,12710,12712,12713,12714,12715,12716,12717,12718"].
Add captions.
Captions are only working for added pictures not for gallery pictures.

Thanks in advance.

skaterlui

**Comment by agriboed** [comment]
Hi, @skaterlui 
You're right. It will be fixed in few days on this week.

**Comment by skaterlui** [comment]
Good morning @agriboed 
one topic for the installation instructions.
Maybe you can mention that only pictures linked to the media file will work. Files linked to the attachment page are not working. This was my hurdle when I tried to get the plugin working for the first time. I could only test this on noteskine theme. Perhaps this is not relevant for other themes.

**Comment by agriboed** [comment]
Fixed
